# Generated by Django 3.2 on 2023-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231108_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
