# Generated by Django 3.2 on 2023-11-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
