# Generated by Django 3.2 on 2023-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', to='products.Product'),
        ),
    ]
